### ISSUE TITLE
Not able to add integration into HA

### ISSUE THREAD

**Issue by AABatteries** [bieniu/ha-zadnego-ale#1]
The integration can't be found in the integrations section in HA - nothing shows up while searching for "żadnego" or "zadnego". Following the supplied My Home Assistant link returns the following: 
```
Error
Config flow could not be loaded
```
Couldn't find the integration in HACS as well. 

Running core-2021.3.4, stable channel

**Comment by bieniu** [comment]
Did you install the integration and restart HA first?

**Comment by AABatteries** [comment]
Do you have to install the integration manually first? If yes then I think it would be helpful to mention this in the readme. Currently it seems like the integration can be installed via HA

**Comment by bieniu** [comment]
Of course you have to install the integration first.

**Comment by bieniu** [comment]
Close via https://github.com/bieniu/ha-zadnego-ale/commit/a2d84ef9caff4d7b5e56e79e5a55493167861980
