### ISSUE TITLE
The website has stopped working

### ISSUE THREAD

**Issue by nethomesh** [bieniu/ha-zadnego-ale#150]
Hello,
The website has stopped working.
Taki problem strona przestała działać.

https://zadnegoale.pl/

![Bez tytułu](https://user-images.githubusercontent.com/35365215/203021031-a01765e3-298e-407d-aae3-9dafca446224.png)

**Comment by bieniu** [comment]
Probably someone forgot to pay for the domains ;)

**Comment by nethomesh** [comment]
It looks like it is.  :-)

**Comment by luka6000** [comment]
> Probably someone forgot to pay for the domain ;)

no to może zmiana źródełka?
https://zyrtec.pl/aktualne-pylenie/
albo to https://www.claritine.pl/prognoza-dla-alergikow/aktualna-prognoza-pylenia

**Comment by bieniu** [comment]
@luka6000 biblioteka używa API żadnego ale, źródła które podałeś udostępniają API?

**Comment by bieniu** [comment]
@palibrzuch Czy API żadnego ale będzie jeszcze dostępne?

**Comment by luka6000** [comment]
@bieniu, myślałem że to scraping. Wygląda na to, że dane pochodzą stąd http://www.obas.pl/kontakt ewentualnie tutaj https://ean.polleninfo.eu/Ean/about Nie widzę publicznych API, więc jedyne co pozostaje to zapytać :)

**Comment by palibrzuch** [comment]
> @palibrzuch Czy API żadnego ale będzie jeszcze dostępne?

Tego nie wiem. Nie wiedziałem, że to jest uzależnione od tego.

**Comment by bieniu** [comment]
@palibrzuch Jak na razie źródło danych nie działa i nie wiadomo czy będzie działać. To nigdy nie było oficjalne API wiec ciężko powiedzieć jaka będzie jego przyszłość.

**Comment by palibrzuch** [comment]
> 

Ok, dzięki za info. Dodatek bardzo fajny był :)

**Comment by sytchi** [comment]
Czy ktoś znalazł jakąś alternatywną integrację dla Home Assistant (np. ze źródeł wymienionych wyżej)? Albo może ktoś planuje stworzyć coś takiego? 
Nie wygląda na to, żeby strona miała się podnieść :-(

**Comment by meritumcom** [comment]
pod f12 np na stronie https://www.twojapogoda.pl/prognoza-polska/slaskie-bytom/ pod Application jest parametr isHometownSet - 277 to jest id po /daily/
w ciągu "allergens":[0,0,1,1,3,0,0,1,0,0,0,1,1,2]}
3. to brzoza
5. to Olsza
14. to topola

**Comment by Krzysztonek** [comment]
Jestem alergikiem, tym bardziej ochoczo kibicuję powrotowi tej integracji. Niestety nie jestem programistą, więc pozostaje mi czekać, dmuchać w trąbkę i machać pomponami... ;)

**Comment by bieniu** [comment]
The host `api.zadnegoale.pl` is down so the service is no longer available.
