### ISSUE TITLE
Integracja zgłasza błąd

### ISSUE THREAD

**Issue by casper255** [bieniu/ha-zadnego-ale#178]
Integracja zgłasza błąd i nie wczytuje danych.

Logger: homeassistant.config_entries
Source: config_entries.py:1133
First occurred: 20:03:59 (1 occurrences)
Last logged: 20:03:59

Config entry 'Śląsk i Wielkopolska' for zadnego_ale integration not ready yet: Invalid response from Zadnego Ale API: null; Retrying in background

**Comment by bieniu** [comment]
Duplicate #150
