### ISSUE TITLE
Problem with API

### ISSUE THREAD

**Issue by koles142** [bieniu/ha-zadnego-ale#23]
Hi,
I'm using interation with region: Sudety. Actually in logs I have an error:

"Config entry 'Sudety' for zadnego_ale integration not ready yet: Invalid response from Zadnego Ale API: null; Retrying in background"

All sensors are unavailable

Version of Żadnego Ale: 0.6.2

Can you check it? Thanks.

**Comment by bieniu** [comment]
API returns `null` so I can't do anything about this problem.

**Comment by koles142** [comment]
Maybe another region is available instead „Sudety”?

**Comment by bieniu** [comment]
Currently, the `Sudety` region works.
