### ISSUE TITLE
zadnegoale.pl is down, probably permanently, integration doesn't work

### ISSUE THREAD

**Issue by kszmich** [bieniu/ha-zadnego-ale#240]
zadnegoale.pl is down, seems that it is permanent. Instead there is a page with text "CyberPanel Installed. You have successfully installed CyberPanel, please remove this page and upload your website. :)"
Integration stopped working.
Seems that it should be removed from HACS.

**Comment by bieniu** [comment]
Duplicate #150

**Comment by kszmich** [comment]
Please remove from HACS.

**Comment by bieniu** [comment]
https://github.com/hacs/default/pull/1848
