### ISSUE TITLE
Change integration language

### ISSUE THREAD

**Issue by 1kohm** [bieniu/ha-zadnego-ale#29]
Hi, 

thank for integration Bieniu it works great therefore I'd like to request for an feature or information how I can change language.
I'm using Home Assistant in English language as it's easier for daily usage and forum troubleshooting. Is it possible to change Entities language names from default HA language to Polish? Would be great to change it automatically rather then translating manually. 

Thanks

**Comment by Ibanezz76** [comment]
My problem is the opposite, I have HA in Polish, but the integration is in English... "Alder Pollen Concentration" for example.
I raise the question of how to change the language :-)
greetings

**Comment by bieniu** [comment]
HA doesn't provide a mechanism to translate entity IDs/names. You have to change them yourself.
