### ISSUE TITLE
ale się wynarodowiło

### ISSUE THREAD

**Issue by michaldamski** [bieniu/ha-zadnego-ale#9]
pięknie wszystko działało i nagle zaczęło do mnie gadać w obcym języku. Trawa to już nie trawa a co gorsza nasza polska wierzba to też już nie wierzba. Wnoszę o repolonizacje.

**Comment by bieniu** [comment]
To jest przygotowanie do dodania komponentu do repozytorium HA. Repolonizacja to tylko w mediach ;)

**Comment by OldShaterhan** [comment]
A jest jakaś opcja pomóc w przywróceniu j. polskiego (nie mówię o logice, ale z tłumaczeniami ew.)? :D

**Comment by bieniu** [comment]
Nie ma w HA mechanizmu tłumaczenia nazwy encji. Są tłumaczenia stanów i one są obsługiwane w integracji.

**Comment by michaldamski** [comment]
a jak działają te tłumaczenia, bo u mnie nazwy stanów również są po angielsku. Gdzieś się definiuje język? 
Może dodać jakiś dodatkowy atrybut z polską nazwą, friendly_name_pl?

**Comment by OldShaterhan** [comment]
https://www.home-assistant.io/docs/configuration/customizing-devices/ coś takiego jakoś do wykorzystania?

**Comment by bieniu** [comment]
@michaldamski Frontend wyświetla stany w języku ustawionym w profilu użytkownika

![Screenshot_20210905-223022](https://user-images.githubusercontent.com/478555/132140589-e4febcd0-4568-4b75-a4bf-ab36f709ba56.jpg)

**Comment by bieniu** [comment]
@OldShaterhan Nazwę encji i friendly name użytkownik może sobie ustawić wedle upodobania. Customizacja nie jest do tego potrzebna

![Uploading Screenshot_20210905-223134.jpg…]()

**Comment by bieniu** [comment]
@OldShaterhan Nazwę encji i friendly name użytkownik może sobie ustawić wedle upodobania. Customizacja nie jest do tego potrzebna

![Screenshot_20210905-223134](https://user-images.githubusercontent.com/478555/132140688-55dccc72-8021-4e40-83f3-d9e8570439b4.jpg)

**Comment by OldShaterhan** [comment]
> @OldShaterhan Nazwę encji i friendly name użytkownik może sobie ustawić wedle upodobania. Customizacja nie jest do tego potrzebna
> 
> ![Screenshot_20210905-223134](https://user-images.githubusercontent.com/478555/132140688-55dccc72-8021-4e40-83f3-d9e8570439b4.jpg)

myślałem, że idzie to zrobić jakoś automatem, żeby nazwy encji z automatu też były polskie, bo ręczne ustawianie tego imo jest trochę słabe, ale to już kwestia samego HA...
